apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-helm-charts
#  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: project1
  url: https://github.com/agepalmist/helm-chart.git