apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: project1-helm-charts
spec:
  interval: 1m0s
  ref:
    branch: project1
  secretRef:
    name: helm-charts
  url: https://github.com/agepalmist/helm-chart.git